title: thunklife
description: Describe your website here.
# Change url to your domain. Leave localhost server or blank when working locally.
url: thunklife.website

# Owner/author information
owner:
  name: thunklife
  email: jessewilliamson@fastmail.fm

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Los_Angeles
future: true

auto: true
permalink: none
pygments: true
markdown: kramdown
server: true
exclude:
- README.md
- Rakefile
