title: wilhelmson
description: Describe your website here.
# Change url to your domain. Leave localhost server or blank when working locally.
url: wilhelmson.github.io

# Owner/author information
owner:
  name: wilhelmson
  email: j.williamson.sd@gmail.com

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Los_Angeles
future: true

auto: true
permalink: none
markdown: kramdown
pygments: true
server: true
exclude:
- README.md
- Rakefile

